server:
  port: 8080
spring:
  application:
    name: EMPLOYEE-MICROSERVICE
  
  # Zipkin server
  zipkin: 
    base-url: http://localhost:9411/ 
  sleuth:
    sampler:
      probability: 1.0 
      
#  Mariadb datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/employee-microservice
    username: root
    password: password   
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  mvc:
   pathmatch:
     matching-strategy: ant-path-matcher
     
 
    
# Eureka client registry
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka  
#  instance:
#     hostname: localhost 


# resilience4j
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      employee-microservice:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
      

